const S={section:null,level:'all',i:0,queue:[],selected:null,checked:false,done:JSON.parse(localStorage.ep_done||'{}'),stats:JSON.parse(localStorage.ep_stats||'{"correct":0,"attempts":0}'),streak:+(localStorage.ep_streak||0),day:localStorage.ep_day||''};
const $=x=>document.querySelector(x), info=[['present-simple','Present Simple','Привычки, факты и регулярные действия','◷'],['present-continuous','Present Continuous','Что происходит сейчас','◌'],['past-simple','Past Simple','Завершённые действия в прошлом','←'],['past-continuous','Past Continuous','Процесс в прошлом','◐'],['present-perfect','Present Perfect','Опыт и результат до настоящего','✓'],['present-perfect-continuous','Present Perfect Continuous','Длительность до настоящего','≈'],['past-perfect','Past Perfect','Раньше другого прошлого','↶'],['future-forms','Future Forms','Will, going to и планы','→'],['conditionals','Conditionals','0, 1, 2 и 3 типы условий','◇'],['seasons','Seasons & Weather','Сезоны и погода','☼'],['translation','Translation','Перевод фраз','文'],['word-order','Word Order','Порядок слов','≡']];
function save(){localStorage.ep_done=JSON.stringify(S.done);localStorage.ep_stats=JSON.stringify(S.stats);localStorage.ep_streak=S.streak;localStorage.ep_day=S.day}
function esc(x){return x.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function norm(x){return x.toLowerCase().trim().replace(/[’']/g,"'").replace(/[.,!?;:]+$/,'').replace(/\s+/g,' ')}
function streak(){let d=new Date().toISOString().slice(0,10);if(S.day!==d){if(S.day){let a=new Date(S.day),b=new Date(d),n=Math.round((b-a)/864e5);S.streak=n===1?S.streak+1:1}else S.streak=1;S.day=d;save()}}
function nav(){ $('#nav').innerHTML=info.map(x=>`<button class="navitem ${S.section===x[0]?'active':''}" data-s="${x[0]}"><span>${x[3]}</span>${x[1]}</button>`).join('');document.querySelectorAll('.navitem').forEach(b=>b.onclick=()=>select(b.dataset.s))}
function cards(){let c=$('#cards');c.innerHTML=info.map((x,n)=>{let a=EXERCISES.filter(e=>e.section===x[0]),d=a.filter(e=>S.done[e.id]).length;return `<article class="card" data-s="${x[0]}"><span class="num">${String(n+1).padStart(2,'0')}</span><h3>${x[1]}</h3><p>${x[2]}</p><div class="bottom"><span>${d}/${a.length} выполнено</span><span>${[...new Set(a.map(e=>e.level))].join(' · ')}</span></div></article>`}).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>select(c.dataset.s))}
function stats(){let d=Object.keys(S.done).length,p=Math.round(d/EXERCISES.length*100);$('#done').textContent=d;$('#pct').textContent=p+'%';$('#bar').style.width=p+'%';$('#mini').textContent=p+'%';$('#streak').textContent=S.streak;$('#best').textContent=S.streak;$('#accuracy').textContent=S.stats.attempts?Math.round(S.stats.correct/S.stats.attempts*100)+'%':'—'}
function select(id){S.section=id;S.i=0;S.queue=EXERCISES.filter(e=>e.section===id&&(S.level==='all'||e.level===S.level));if(!S.queue.length)S.queue=EXERCISES.filter(e=>e.section===id);nav();practice();$('#practice').scrollIntoView({behavior:'smooth'})}
function practice(){if(!S.section)return;let e=S.queue[S.i%S.queue.length],title=info.find(x=>x[0]===S.section)[1];$('#ptitle').textContent=title;$('#crumb').textContent=title;$('#counter').textContent=`${S.i+1} / ${S.queue.length}`;$('#level').textContent=e.level;S.selected=null;S.checked=false;let body='';
if(['fill','translate','error'].includes(e.type))body=`<input class="answer" id="ans" placeholder="${e.type==='translate'?'Напиши перевод на английском…':'Введи ответ…'}" autocomplete="off">`;
else if(e.type==='choice')body=`<div class="options">${e.options.map((o,i)=>`<button class="option" data-i="${i}">${esc(o)}</button>`).join('')}</div>`;
else{let w=e.question.split(' / ').sort(()=>Math.random()-.5);body=`<div class="assembled" id="assembled"></div><div class="chips">${w.map(x=>`<button class="chip" data-w="${esc(x)}">${esc(x)}</button>`).join('')}</div>`}
let label={fill:'впиши ответ',translate:'переведи на английский',error:'исправь ошибку',choice:'выбери ответ',reorder:'собери предложение'}[e.type];
$('#exercise').innerHTML=`<div class="qtype">${label}</div><div class="question">${esc(e.question)}</div>${body}<div class="hint">${e.type==='reorder'?'Нажимай на слова в нужном порядке.':'Ответ проверяется без учёта регистра.'}</div><div class="row"><button class="check" id="check">Проверить</button><span id="feedback" class="feedback"></span><button class="next" id="next" style="display:none">Следующее →</button></div>`;
document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{S.selected=+b.dataset.i;document.querySelectorAll('.option').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')});
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{if(b.classList.contains('used'))return;b.classList.add('used');let x=document.createElement('span');x.textContent=b.dataset.w;x.dataset.w=b.dataset.w;$('#assembled').appendChild(x)});
$('#check').onclick=()=>check(e);$('#next').onclick=()=>{S.i=(S.i+1)%S.queue.length;practice()};$('#ans')?.addEventListener('keydown',x=>{if(x.key==='Enter')check(e)})}
function check(e){if(S.checked)return;let u='',ok=false;if(['fill','translate','error'].includes(e.type)){u=$('#ans').value;ok=[e.answer,e.alt].filter(Boolean).some(a=>norm(u)===norm(a))}else if(e.type==='choice'){ok=S.selected!==null&&e.options[S.selected]===e.answer}else{u=[...$('#assembled').children].map(x=>x.dataset.w).join(' ');ok=norm(u)===norm(e.answer)}S.stats.attempts++;if(ok){S.stats.correct++;S.done[e.id]=true;streak()}save();S.checked=true;stats();let f=$('#feedback');f.className='feedback '+(ok?'ok':'bad');f.innerHTML=ok?'✓ Верно':`✕ Правильный ответ: <strong>${esc(e.answer)}</strong>`;$('#check').style.display='none';$('#next').style.display='inline-block'}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.level=b.dataset.level;cards();if(S.section)select(S.section)});
$('#start').onclick=()=>select(S.section||'present-simple');$('#random').onclick=()=>{let e=EXERCISES[Math.floor(Math.random()*EXERCISES.length)];select(e.section);S.i=S.queue.findIndex(x=>x.id===e.id);practice()};$('#reset').onclick=()=>{if(confirm('Сбросить весь прогресс?')){S.done={};S.stats={correct:0,attempts:0};S.streak=0;S.day='';save();stats();cards()}};
$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.ep_dark=document.body.classList.contains('dark')};if(localStorage.ep_dark==='true')document.body.classList.add('dark');$('#menu').onclick=()=>$('#side').classList.add('open');$('#close').onclick=()=>$('#side').classList.remove('open');streak();nav();cards();stats();